sudo: required

services:
- docker

before_install:
- docker pull centos:7.4.1708
- docker pull centos:7.5.1804
- docker pull centos:7.6.1810

env:
 global:
   - CEPH_VERSION=nautilus
   - KUBE_VERSION=1.15.4
   - DOCKER_VERSION=1.13.1
 
script:
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:7.4.1708
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y https://download.ceph.com/rpm-${CEPH_VERSION}/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
   yum install -y yum-utils &&
   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo &&
   mkdir -p /rpms/centos74 &&
   yum remove -y python-chardet chrony &&
   yum -y install --downloadonly --downloaddir=/rpms/centos74 docker docker-python docker-compose python-chardet python-requests &&
   yum -y install --downloadonly --downloaddir=/rpms/centos74 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz &&
   yum -y install --downloadonly --downloaddir=/rpms/centos74 ceph-deploy ceph ceph-radosgw radosgw-agent rbd-nbd rbd-mirror open-vm-tools nfs-utils && 
   yum -y install --downloadonly --downloaddir=/rpms/centos74 kubernetes-cni kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION}"
  docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:7.5.1804
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y https://download.ceph.com/rpm-${CEPH_VERSION}/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
   yum install -y yum-utils &&
   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo &&
   mkdir -p /rpms/centos75 &&
   yum remove -y python-chardet chrony &&
   yum -y install --downloadonly --downloaddir=/rpms/centos75 docker docker-python docker-compose python-chardet python-requests &&
   yum -y install --downloadonly --downloaddir=/rpms/centos75 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz &&
   yum -y install --downloadonly --downloaddir=/rpms/centos75 ceph-deploy ceph ceph-radosgw radosgw-agent rbd-nbd rbd-mirror open-vm-tools nfs-utils && 
   yum -y install --downloadonly --downloaddir=/rpms/centos75 kubernetes-cni kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION}"
  docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:7.6.1810
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y https://download.ceph.com/rpm-${CEPH_VERSION}/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
   yum install -y yum-utils &&
   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo &&
   mkdir -p /rpms/centos76 &&
   yum remove -y python-chardet chrony &&
   yum -y install --downloadonly --downloaddir=/rpms/centos76 docker docker-python docker-compose python-chardet python-requests &&
   yum -y install --downloadonly --downloaddir=/rpms/centos76 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz &&
   yum -y install --downloadonly --downloaddir=/rpms/centos76 ceph-deploy ceph ceph-radosgw radosgw-agent rbd-nbd rbd-mirror open-vm-tools nfs-utils && 
   yum -y install --downloadonly --downloaddir=/rpms/centos76 kubernetes-cni kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} &&
   yum install -y createrepo &&
   yum clean all &&
   createrepo /rpms"
   
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t registry.cn-shenzhen.aliyuncs.com/hi30567721/yum-repo:v1.15.4 .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-shenzhen.aliyuncs.com
- docker push registry.cn-shenzhen.aliyuncs.com/hi30567721/yum-repo:v1.15.4
